from enum import StrEnum


class Destination(StrEnum):
    DOJO_COURTYARD = "dojo_courtyard"
    FOREST = "forest"
    ICEBERG = "iceberg"
    SKII_HILL = "skii_hill"
    SKII_VILLAGE = "skii_village"
    SNOW_FORTS = "snow_forts"
    STADIUM = "stadium"
    THE_BEACH = "the_beach"
    THE_COVE = "the_cove"
    THE_DOCK = "the_dock"
    THE_PLAZA = "the_plaza"
    MINE = "mine"
    THE_TOWN = "the_town"
    WELCOME_ROOM = "welcome_room"
    LIGHTHOUSE = "lighthouse"
    BEACON = "beacon"
    SKII_LODGE = "skii_lodge"
    SKII_LODGE_ATTIC = "skii_lodge_attic"
    SPORTS_SHOP = "sports_shop"
    SPY_HEADQUARTERS = "spy_headquarters"
    NIGHTCLUB = "nightclub"
    LOUNGE = "lounge"
