from enum import StrEnum


class Destination(StrEnum):
    DOJO_COURTYARD = "dojo_courtyard"
    FOREST = "forest"
    ICEBERG = "iceberg"
    SKII_HILL = "skii_hill"
    SKII_VILLAGE = "skii_village"
    SNOW_FORTS = "snow_forts"
    STADIUM = "stadium"
    THE_BEACH = "the_beach"
    THE_COVE = "the_cove"
    THE_DOCK = "the_dock"
    THE_PLAZA = "the_plaza"
    MINE = "mine"
    THE_TOWN = "the_town"
    WELCOME_ROOM = "welcome_room"
    LIGHTHOUSE = "lighthouse"
    BEACON = "beacon"
    SKII_LODGE = "skii_lodge"
    SKII_LODGE_ATTIC = "skii_lodge_attic"
    SPORTS_SHOP = "sports_shop"
    SPY_HEADQUARTERS = "spy_headquarters"
    NIGHTCLUB = "nightclub"
    LOUNGE = "lounge"
    COFFEE_SHOP = "coffee_shop"
    BOOK_ROOM = "book_room"
    GIFT_SHOP = "gift_shop"
    GIFT_SHOP_OFFICE = "gift_shop_office"
    TOUR_HQ = "tour_hq"
    TOUR_HQ_LOOKOUT = "tour_hq_lookout"
    PET_SHOP = "pet_shop"
    PET_SHOP_PUFFLE_PARK = "pet_shop_puffle_park"
    THE_STAGE = "the_stage"
    PIZZA_PARLOR = "pizza_parlor"
