# Form implementation generated from reading ui file 'src/club_penguin_ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(480, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(parent=Login)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=Login)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(parent=Login)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=Login)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.passwordLineEdit)
        self.serverLabel = QtWidgets.QLabel(parent=Login)
        self.serverLabel.setObjectName("serverLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.serverLabel)
        self.serverLineEdit = QtWidgets.QLineEdit(parent=Login)
        self.serverLineEdit.setObjectName("serverLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.serverLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsLayout.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(parent=Login)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)
        self.loginButton = QtWidgets.QPushButton(parent=Login)
        self.loginButton.setObjectName("loginButton")
        self.buttonsLayout.addWidget(self.loginButton)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.usernameLabel.setText(_translate("Login", "Username"))
        self.passwordLabel.setText(_translate("Login", "Password"))
        self.serverLabel.setText(_translate("Login", "Server"))
        self.cancelButton.setText(_translate("Login", "Cancel"))
        self.loginButton.setText(_translate("Login", "Login"))
