# Form implementation generated from reading ui file 'src/club_penguin_ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(748, 713)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.mainTabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.actionsTab = QtWidgets.QWidget()
        self.actionsTab.setObjectName("actionsTab")
        self.actionsTabLayout = QtWidgets.QVBoxLayout(self.actionsTab)
        self.actionsTabLayout.setObjectName("actionsTabLayout")
        self.actionsGroupBox = QtWidgets.QGroupBox(parent=self.actionsTab)
        self.actionsGroupBox.setObjectName("actionsGroupBox")
        self.actionsGroupLayout = QtWidgets.QVBoxLayout(self.actionsGroupBox)
        self.actionsGroupLayout.setObjectName("actionsGroupLayout")
        self.actionListWidget = QtWidgets.QListWidget(parent=self.actionsGroupBox)
        self.actionListWidget.setObjectName("actionListWidget")
        self.actionsGroupLayout.addWidget(self.actionListWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.currentRunningActionLabel = QtWidgets.QLabel(parent=self.actionsGroupBox)
        self.currentRunningActionLabel.setObjectName("currentRunningActionLabel")
        self.gridLayout.addWidget(self.currentRunningActionLabel, 1, 0, 1, 1)
        self.abortActionButton = QtWidgets.QPushButton(parent=self.actionsGroupBox)
        self.abortActionButton.setObjectName("abortActionButton")
        self.gridLayout.addWidget(self.abortActionButton, 2, 0, 1, 1)
        self.launchActionButton = QtWidgets.QPushButton(parent=self.actionsGroupBox)
        self.launchActionButton.setObjectName("launchActionButton")
        self.gridLayout.addWidget(self.launchActionButton, 2, 1, 1, 1)
        self.actionsGroupLayout.addLayout(self.gridLayout)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.actionsGroupBox)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 200))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.actionsGroupLayout.addWidget(self.plainTextEdit)
        self.actionsTabLayout.addWidget(self.actionsGroupBox)
        self.mainTabWidget.addTab(self.actionsTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.settingsTabLayout = QtWidgets.QVBoxLayout(self.settingsTab)
        self.settingsTabLayout.setObjectName("settingsTabLayout")
        self.mainTabWidget.addTab(self.settingsTab, "")
        self.verticalLayout.addWidget(self.mainTabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionActions = QtGui.QAction(parent=MainWindow)
        self.actionActions.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionActions.setObjectName("actionActions")
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        self.actionSettings.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionSettings.setObjectName("actionSettings")

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Club Penguin Bot"))
        self.titleLabel.setText(_translate("MainWindow", "Club Penguin Bot"))
        self.actionsGroupBox.setTitle(_translate("MainWindow", "Actions"))
        self.currentRunningActionLabel.setText(_translate("MainWindow", "Current Running Action: <action-here>"))
        self.abortActionButton.setText(_translate("MainWindow", "Abort Action"))
        self.launchActionButton.setText(_translate("MainWindow", "Launch Action"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.actionsTab), _translate("MainWindow", "Actions"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.settingsTab), _translate("MainWindow", "Settings"))
        self.actionActions.setText(_translate("MainWindow", "Actions"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
