# Form implementation generated from reading ui file 'src/club_penguin_ui/settings.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(480, 271)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(parent=Settings)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=Settings)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(parent=Settings)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=Settings)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.passwordLineEdit)
        self.serverLabel = QtWidgets.QLabel(parent=Settings)
        self.serverLabel.setObjectName("serverLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.serverLabel)
        self.serverLineEdit = QtWidgets.QLineEdit(parent=Settings)
        self.serverLineEdit.setObjectName("serverLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.serverLineEdit)
        self.urlLabel = QtWidgets.QLabel(parent=Settings)
        self.urlLabel.setObjectName("urlLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.urlLabel)
        self.urlLineEdit = QtWidgets.QLineEdit(parent=Settings)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.urlLineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.loginButton = QtWidgets.QPushButton(parent=Settings)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.loggedInStatusLabel = QtWidgets.QLabel(parent=Settings)
        self.loggedInStatusLabel.setObjectName("loggedInStatusLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.loggedInStatusLabel)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsLayout.addItem(spacerItem1)
        self.exitButton = QtWidgets.QPushButton(parent=Settings)
        self.exitButton.setObjectName("exitButton")
        self.buttonsLayout.addWidget(self.exitButton)
        self.saveButton = QtWidgets.QPushButton(parent=Settings)
        self.saveButton.setObjectName("saveButton")
        self.buttonsLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.usernameLabel.setText(_translate("Settings", "Username"))
        self.passwordLabel.setText(_translate("Settings", "Password"))
        self.serverLabel.setText(_translate("Settings", "Server"))
        self.urlLabel.setText(_translate("Settings", "URL"))
        self.loginButton.setText(_translate("Settings", "Login"))
        self.loggedInStatusLabel.setText(_translate("Settings", "Logged in: False"))
        self.exitButton.setText(_translate("Settings", "Exit"))
        self.saveButton.setText(_translate("Settings", "Save"))
